# Python Lists

## Creating

In [2]:
# this is a python list
a = [42, 7, 13, 24601, 2001, 3.50]

In [3]:
# this is a list comprehension -- think of it as a sexy for loop

# the following gives us a list in which we multiplied each element in a by 2
z = [i * 2 for i in a]
z

[84, 14, 26, 49202, 4002, 7.0]

## Indexing

In [4]:
# you can index into it
a[0]

42

In [6]:
# what's the 3rd element?
a[2]

13

In [7]:
# indices can also be negative
# this gives you the last element
a[-1]

3.5

## Slicing

In [8]:
# you can also get subsets of the list with slicing
#     a[start:end]
# [start, end)

# this returns the 3rd and 4th entries (indices 2 and 3 -- note we exclude 4!)
a[2:4]

[13, 24601]

In [9]:
# if you leave one side blank, it automatically goes all the way
# first five:
a[:5]

[42, 7, 13, 24601, 2001]

In [12]:
# how do you get the last three elements?
a[-3:]

[24601, 2001, 3.5]

In [13]:
# slices can also skip numbers
# a[start:end:interval]

# this gives us every other number, starting with the first
a[::2]

[42, 13, 2001]

In [14]:
# the interval can also be negative
# what does that do?

a[::-2]

[3.5, 24601, 7]

# Numpy

In [15]:
import numpy as np

## Creating

In [16]:
# numpy arrays can be created from a python list
b = np.array(a)
b

array([4.2000e+01, 7.0000e+00, 1.3000e+01, 2.4601e+04, 2.0010e+03,
       3.5000e+00])

Right now, it looks an awful like a python list, but there are some key points you should know.

numpy arrays are:
- homogeneous (all elements in an array have the same type)
- multidimensional

In [17]:
# Homogeneous: all numpy arrays have an associated data type.
# numbers are usually ints or floats
b.dtype

dtype('float64')

In [18]:
# Multidimensional: numpy arrays can have multiple dimensions, like a nested list.
# We can reshape b into a 3x2 matrix
# Note: this doesn't change b. That's why we assign it to a new variable: m
m = b.reshape(3, 2)
m

array([[4.2000e+01, 7.0000e+00],
       [1.3000e+01, 2.4601e+04],
       [2.0010e+03, 3.5000e+00]])

In [19]:
# Each dimension is called an axis
# The size across each axis is called the shape
# These are two very important concepts!
m.shape

(3, 2)

In [20]:
m[1:3,1]

array([2.4601e+04, 3.5000e+00])

## Indexing

In [64]:
# We index into numpy arrays much the same way as python lists.
b[0]
b

array([4.2000e+01, 7.0000e+00, 1.3000e+01, 2.4601e+04, 2.0010e+03,
       3.5000e+00])

In [22]:
# But N-dimensional arrays mean we can be more expressive with indexing
# This gives us [0th index of axis 0, 1st index of axis 1]
# You can think of this as a grid
# Alternatively, this is like m[0][1]
m[0, 1]

7.0

In [23]:
# We can also pass in multiple indices as a list
# This gives us the 1st, 2nd, and 5th values of b
b[[0, 1, 4]]

array([  42.,    7., 2001.])

In [69]:
# Let's combine these two facts to get the 2nd and 3rd items in the second column of m
m[1:,1]

array([2.4601e+04, 3.5000e+00])

In [25]:
# We can also incorporate our previous knowledge of slices.
# So to get the second column
# This gives us the entire range on axis 0, and only the 1st index on axis 1
m[:,1]

array([7.0000e+00, 2.4601e+04, 3.5000e+00])

## Math

In [26]:
# numpy gives us a lot of math functions to work with
# I'll only show you a couple, but you can find them all in the documentation

np.sum(b)  # guess what this does?

26667.5

In [27]:
np.mean(b)  # and this?

4444.583333333333

In [28]:
# for convenience, you can also call
b.mean()

4444.583333333333

In [29]:
m

array([[4.2000e+01, 7.0000e+00],
       [1.3000e+01, 2.4601e+04],
       [2.0010e+03, 3.5000e+00]])

In [33]:
# you can also apply these functions to only one axis
# only sum across rows (read: apply the sum to axis 1)
np.sum(m, axis=1)

array([ 2056. , 24611.5])

In [31]:
# numpy has a concept called podcasting
# It tries to coerce non-matching shapes.
# 2 is a scalar, but we can still multiply m by it
# it just repeats the 2 across all instances of m
m * 2

array([[8.4000e+01, 1.4000e+01],
       [2.6000e+01, 4.9202e+04],
       [4.0020e+03, 7.0000e+00]])

# Pandas

In [34]:
import pandas as pd

Matplotlib is building the font cache using fc-list. This may take a moment.


## Creating

Pandas lets us read all sorts of data into a Dataframe. Think of this as a series of lists. Let's look at an example.

In [152]:
df = pd.read_csv("./cereal.csv")
type(df)

pandas.core.frame.DataFrame

In [37]:
# head() gives us the first 10 rows in the dataframe (pd.DataFrame)
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [42]:
# you can think of each column as a list (or a 1D numpy array)
# in practice, these are called pandas Series (pd.Series)
# you can index into the dataframe with a string to get one column
df["name"].to_numpy()

array(['100% Bran', '100% Natural Bran', 'All-Bran',
       'All-Bran with Extra Fiber', 'Almond Delight',
       'Apple Cinnamon Cheerios', 'Apple Jacks', 'Basic 4', 'Bran Chex',
       'Bran Flakes', "Cap'n'Crunch", 'Cheerios', 'Cinnamon Toast Crunch',
       'Clusters', 'Cocoa Puffs', 'Corn Chex', 'Corn Flakes', 'Corn Pops',
       'Count Chocula', "Cracklin' Oat Bran", 'Cream of Wheat (Quick)',
       'Crispix', 'Crispy Wheat & Raisins', 'Double Chex', 'Froot Loops',
       'Frosted Flakes', 'Frosted Mini-Wheats',
       'Fruit & Fibre Dates; Walnuts; and Oats', 'Fruitful Bran',
       'Fruity Pebbles', 'Golden Crisp', 'Golden Grahams',
       'Grape Nuts Flakes', 'Grape-Nuts', 'Great Grains Pecan',
       'Honey Graham Ohs', 'Honey Nut Cheerios', 'Honey-comb',
       'Just Right Crunchy  Nuggets', 'Just Right Fruit & Nut', 'Kix',
       'Life', 'Lucky Charms', 'Maypo',
       'Muesli Raisins; Dates; & Almonds',
       'Muesli Raisins; Peaches; & Pecans', 'Mueslix Crispy Blend',
  

In [43]:
type(df["name"])

pandas.core.series.Series

## Pandas Series vs Numpy Arrays

In [48]:
# There are many similarities between pd.Series and np.ndarray
# for example:
df["carbo"].mean()

14.597402597402597

In [45]:
# In fact, we can turn pd.Series into a numpy array
# again, this returns a numpy array -- df["carbo"] doesn't change.
df["carbo"].to_numpy()

array([ 5. ,  8. ,  7. ,  8. , 14. , 10.5, 11. , 18. , 15. , 13. , 12. ,
       17. , 13. , 13. , 12. , 22. , 21. , 13. , 12. , 10. , 21. , 21. ,
       11. , 18. , 11. , 14. , 14. , 12. , 14. , 13. , 11. , 15. , 15. ,
       17. , 13. , 12. , 11.5, 14. , 17. , 20. , 21. , 12. , 12. , 16. ,
       16. , 16. , 17. , 15. , 15. , 21. , 18. , 13.5, 11. , 20. , 13. ,
       10. , 14. , -1. , 14. , 10.5, 15. , 23. , 22. , 16. , 19. , 20. ,
        9. , 16. , 15. , 21. , 15. , 16. , 21. , 13. , 17. , 17. , 16. ])

In [46]:
# The key difference is that Series are indexed
# See the 0, 1, ... 76 on the left? That is the index of each item.
# Right now they are just positions, but theoretically they can be any unique identifier for the row
# Think: ID, username, etc
df["carbo"].index

RangeIndex(start=0, stop=77, step=1)

## Indexing into DataFrames and Series

In [49]:
# Indexing is a little bit different in pandas.
# One parallel to what you've been used to is .loc[]
# this is the row at index 0
df.loc[0]

name        100% Bran
mfr                 N
type                C
calories           70
protein             4
fat                 1
sodium            130
fiber              10
carbo               5
sugars              6
potass            280
vitamins           25
shelf               3
weight              1
cups             0.33
rating         68.403
Name: 0, dtype: object

In [50]:
# multiple indices work
df.loc[[1, 2, 3]]

name mfr type  calories  protein  fat  sodium  fiber  \
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912

In [51]:
# caveat: remember that pandas doesn't require zero-indexing. indices can be anything.
# this means slicing might not work all the time (what would df.loc["asdf":"hjkl"] even mean?)
# in the cases that you actually want to index by row number, you can always do that with .iloc[]
# again, this will behave the same as .loc[] with our dataset because our data is 0-indexed
df.iloc[0]

name        100% Bran
mfr                 N
type                C
calories           70
protein             4
fat                 1
sodium            130
fiber              10
carbo               5
sugars              6
potass            280
vitamins           25
shelf               3
weight              1
cups             0.33
rating         68.403
Name: 0, dtype: object

In [55]:
# We can also use boolean indexing by passing a list of booleans like so:
df[[True] + [False] * 76]
# Let me explain:
# - [True] + [False] * 76 gives us a list that looks like [True, False, ..., False] with 1 True and 76 Falses
# - This matches the number of rows in our data (77)
# - pandas returns all the rows with a corresponding True (in this case, only the first one)

name mfr type  calories  protein  fat  sodium  fiber  carbo  sugars  \
0  100% Bran   N    C        70        4    1     130   10.0    5.0       6   

   potass  vitamins  shelf  weight  cups     rating  
0     280        25      3     1.0  0.33  68.402973

In [56]:
# This is powerful because we can also make comparisons with Series and values.
df["protein"] > 3

0      True
1     False
2      True
3      True
4     False
      ...  
72    False
73    False
74    False
75    False
76    False
Name: protein, Length: 77, dtype: bool

In [57]:
# Combining these two things, we have a very expressive way of filtering.
# This gives us all the rows in which the protein is greater than 3.
df[df["protein"] > 3]

name mfr type  calories  protein  fat  \
0                           100% Bran   N    C        70        4    1   
2                            All-Bran   K    C        70        4    1   
3           All-Bran with Extra Fiber   K    C        50        4    0   
11                           Cheerios   G    C       110        6    2   
41                               Life   Q    C       100        4    2   
43                              Maypo   A    H       100        4    1   
44   Muesli Raisins; Dates; & Almonds   R    C       150        4    3   
45  Muesli Raisins; Peaches; & Pecans   R    C       150        4    3   
56                 Quaker Oat Squares   Q    C       100        4    1   
57                     Quaker Oatmeal   Q    H       100        5    2   
67                          Special K   K    C       110        6    0   

    sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0      130   10.0    5.0       6     280        25      3     1.0  0.33   
2      260    9.0    7.0       5     320        25      3     1.0  0.33   
3      140   14.0    8.0       0     330        25      3     1.0  0.50   
11     290    2.0   17.0       1     105        25      1     1.0  1.25   
41     150    2.0   12.0       6      95        25      2     1.0  0.67   
43       0    0.0   16.0       3      95        25      2     1.0  1.00   
44      95    3.0   16.0      11     170        25      3     1.0  1.00   
45     150    3.0   16.0      11     170        25      3     1.0  1.00   
56     135    2.0   14.0       6     110        25      3     1.0  0.50   
57       0    2.7   -1.0      -1     110         0      1     1.0  0.67   
67     230    1.0   16.0       3      55        25      1     1.0  1.00   

       rating  
0   68.402973  
2   59.425505  
3   93.704912  
11  50.764999  
41  45.328074  
43  54.850917  
44  37.136863  
45  34.139765  
56  49.511874  
57  50.828392  
67  53.131324

## Manipulating Series

Often when we're preprocessing data, we want to make uniform changes to a specific column. We can do this by applying functions.

In [58]:
# Suppose we want to make the cereals more appetizing.
# Let's add "Delicious " to the beginning of every name.

# The pattern is we define a function for a single entry
def make_delicious(name):
    return "Delicious " + name

# and then call apply on the series to apply the function to each element in the series
df["name"].apply(make_delicious)

0                     Delicious 100% Bran
1             Delicious 100% Natural Bran
2                      Delicious All-Bran
3     Delicious All-Bran with Extra Fiber
4                Delicious Almond Delight
                     ...                 
72                      Delicious Triples
73                         Delicious Trix
74                   Delicious Wheat Chex
75                     Delicious Wheaties
76          Delicious Wheaties Honey Gold
Name: name, Length: 77, dtype: object

In [59]:
# this returns the changes, but doesn't apply them in place.
# that means on our original dataframe, the cereals are still bland
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [60]:
# we can fix this by assigning the new names to the column.
df["name"] = df["name"].apply(make_delicious)
df.head()

name mfr type  calories  protein  fat  \
0                  Delicious 100% Bran   N    C        70        4    1   
1          Delicious 100% Natural Bran   Q    C       120        3    5   
2                   Delicious All-Bran   K    C        70        4    1   
3  Delicious All-Bran with Extra Fiber   K    C        50        4    0   
4             Delicious Almond Delight   R    C       110        2    2   

   sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0     130   10.0    5.0       6     280        25      3     1.0  0.33   
1      15    2.0    8.0       8     135         0      3     1.0  1.00   
2     260    9.0    7.0       5     320        25      3     1.0  0.33   
3     140   14.0    8.0       0     330        25      3     1.0  0.50   
4     200    1.0   14.0       8      -1        25      3     1.0  0.75   

      rating  
0  68.402973  
1  33.983679  
2  59.425505  
3  93.704912  
4  34.384843

In [84]:
# here's another example.
# Jackson is a skeptic and doesn't believe calling things "Delicious" makes them taste better.
# But he does think adding sugar will make them taste better.
# How can we add 10 grams of sugar to every cereal?
df["sugars"] = df["sugars"] + 10
df.head()

name mfr type  calories  protein  fat  \
0                  Delicious 100% Bran   N    C        70        4    1   
1          Delicious 100% Natural Bran   Q    C       120        3    5   
2                   Delicious All-Bran   K    C        70        4    1   
3  Delicious All-Bran with Extra Fiber   K    C        50        4    0   
4             Delicious Almond Delight   R    C       110        2    2   

   sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0     130   10.0    5.0      16     280        25      3     1.0  0.33   
1      15    2.0    8.0      18     135         0      3     1.0  1.00   
2     260    9.0    7.0      15     320        25      3     1.0  0.33   
3     140   14.0    8.0      10     330        25      3     1.0  0.50   
4     200    1.0   14.0      18      -1        25      3     1.0  0.75   

      rating  
0  68.402973  
1  33.983679  
2  59.425505  
3  93.704912  
4  34.384843

## Groups and Aggregates

When we have lots and lots of data, it's more useful to look at aggregate statistics like the mean or median. But sometimes we lose too much detail aggregating across the whole dataset.

The solution is to aggregate across groups. For example, maybe we're less interested in the mean calorie count of all cereals and more interested in the mean for each manufacturer.

In [85]:
# First, we can see how many (and which) unique manufacturers there are
# Note: this gives us a numpy array
df["mfr"].unique()

array(['N', 'Q', 'K', 'R', 'G', 'P', 'A'], dtype=object)

In [153]:
# Now let's group by the manufacturers
# This gives us a groupby object across the dataframe
mfrs = df.groupby("mfr")
mfrs

In [87]:
# what happens if we try to access the calories column?
mfrs["calories"]

In [88]:
# now let's try to get the mean
mfrs["calories"].mean()

mfr
A    100.000000
G    111.363636
K    108.695652
N     86.666667
P    108.888889
Q     95.000000
R    115.000000
Name: calories, dtype: float64

In [89]:
# we can also aggregate across multiple columns, and even use different aggregations
# let's get the average calorie count but the maximum protein
mfrs[["calories", "protein"]].agg({"calories": "mean", "protein": "max"})

calories  protein
mfr                     
A    100.000000        4
G    111.363636        6
K    108.695652        6
N     86.666667        4
P    108.888889        3
Q     95.000000        5
R    115.000000        4

# Exercises

Unless otherwise noted, these should be one line of code.

In [128]:
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]

# get a list containing the last 3 elements of a
b = a[-3:]
# reverse the list
b.reverse()
# get a list where each entry in a is cubed (so the new list is [1, 4, 9, 16, 25, 36])
for i in range(len(b)):
    b[i] =  b[i]* b[i]*b[i]
b

[216, 125, 64]

In [103]:
# create a numpy array from this list
b = np.array(a) # change this
b

array([1, 2, 3, 4, 5, 6])

In [104]:
# find the mean of b
b.mean()

3.5

In [106]:
# change b from a length-6 list to a 2x3 matrix
b = b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
# find the mean value of each row
np.mean(b, axis=1) 

array([2., 5.])

In [109]:
# find the mean value of each column
np.mean(b, axis=0) 

array([2.5, 3.5, 4.5])

In [110]:
# find the third column of b
b[:, 2]

array([3, 6])

In [112]:
# get a list where each entry in b is cubed (so the new numpy array is [1, 4, 9, 16, 25, 36])
# use a different (numpy-specific) approach
cubed = np.power(b, 3)
cubed

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [154]:
# load in the "starbucks.csv" dataset
df = pd.read_csv("./starbucks.csv")
df

Beverage_category                                      Beverage  \
0                        Coffee                                 Brewed Coffee   
1                        Coffee                                 Brewed Coffee   
2                        Coffee                                 Brewed Coffee   
3                        Coffee                                 Brewed Coffee   
4       Classic Espresso Drinks                                   Caffè Latte   
..                          ...                                           ...   
237  Frappuccino® Blended Crème  Strawberries & Crème (Without Whipped Cream)   
238  Frappuccino® Blended Crème          Vanilla Bean (Without Whipped Cream)   
239  Frappuccino® Blended Crème          Vanilla Bean (Without Whipped Cream)   
240  Frappuccino® Blended Crème          Vanilla Bean (Without Whipped Cream)   
241  Frappuccino® Blended Crème          Vanilla Bean (Without Whipped Cream)   

          Beverage_prep  Calories  Total Fat (g)  Trans Fat (g)   \
0                 Short         3            0.1             0.0   
1                  Tall         4            0.1             0.0   
2                Grande         5            0.1             0.0   
3                 Venti         5            0.1             0.0   
4     Short Nonfat Milk        70            0.1             0.1   
..                  ...       ...            ...             ...   
237             Soymilk       320            3 2             0.4   
238    Tall Nonfat Milk       170            0.1             0.1   
239          Whole Milk       200            3.5             2.0   
240             Soymilk       180            1.5             0.2   
241  Grande Nonfat Milk       240            0.1             0.1   

     Saturated Fat (g)   Sodium (mg)   Total Carbohydrates (g)   \
0                  0.0             0                          5   
1                  0.0             0                         10   
2                  0.0             0                         10   
3                  0.0             0                         10   
4                  0.0             5                         75   
..                 ...           ...                        ...   
237                0.0             0                        250   
238                0.0             0                        160   
239                0.1            10                        160   
240                0.0             0                        160   
241                0.0             5                        230   

     Cholesterol (mg)   Dietary Fibre (g)   Sugars (g)   Protein (g)   \
0                   0                   0            0            0.3   
1                   0                   0            0            0.5   
2                   0                   0            0            1.0   
3                   0                   0            0            1.0   
4                  10                   0            9            6.0   
..                ...                 ...          ...            ...   
237                67                   1           64            5.0   
238                39                   0           38            4.0   
239                39                   0           38            3.0   
240                37                   1           35            3.0   
241                56                   0           55            5.0   

    Vitamin A (% DV)  Vitamin C (% DV)  Calcium (% DV)  Iron (% DV)   \
0                  0%               0%               0%           0%   
1                  0%               0%               0%           0%   
2                  0%               0%               0%           0%   
3                  0%               0%               2%           0%   
4                 10%               0%              20%           0%   
..                ...              ...              ...          ...   
237                6%               8%

In [135]:
# this is nutritional info for starbucks items
# let's see if we can answer some questions

# what is the average # calories across all items?
np.mean(df["Calories"])

193.87190082644628

In [141]:
# how many different categories of beverages are there?
len(df["Beverage"].unique())

33

In [170]:
# what is the average # calories for each beverage category?
df.groupby("Beverage_category")["Calories"].mean()

Index(['Beverage_category', 'Beverage', 'Beverage_prep', 'Calories',
       ' Total Fat (g)', 'Trans Fat (g) ', 'Saturated Fat (g)', ' Sodium (mg)',
       ' Total Carbohydrates (g) ', 'Cholesterol (mg)', ' Dietary Fibre (g)',
       ' Sugars (g)', ' Protein (g) ', 'Vitamin A (% DV) ', 'Vitamin C (% DV)',
       ' Calcium (% DV) ', 'Iron (% DV) ', 'Caffeine (mg)'],
      dtype='object')

In [179]:
# what beverage preparation includes the most sugar?
df[df[' Sugars (g)'] == df[' Sugars (g)'].max()]

Beverage_category                           Beverage  \
214  Frappuccino® Blended Coffee  Java Chip (Without Whipped Cream)   
215  Frappuccino® Blended Coffee  Java Chip (Without Whipped Cream)   

         Beverage_prep  Calories  Total Fat (g)  Trans Fat (g)   \
214  Venti Nonfat Milk       420              5             4.0   
215         Whole Milk       460             10             7.0   

     Saturated Fat (g)   Sodium (mg)   Total Carbohydrates (g)   \
214                0.0             5                        340   
215                0.2            15                        340   

     Cholesterol (mg)   Dietary Fibre (g)   Sugars (g)   Protein (g)   \
214                90                   2           84            7.0   
215                90                   2           84            7.0   

    Vitamin A (% DV)  Vitamin C (% DV)  Calcium (% DV)  Iron (% DV)   \
214               10%               0%              20%          35%   
215                6%               0%              15%          35%   

    Caffeine (mg)  
214           145  
215           145

In [209]:
# what is the average % daily value calcium content for each beverage?
# HINT: make sure your columns have the datatypes you want
# (you can use more than one line for this one)
df[" Calcium (% DV) "] = np.float_(df[" Calcium (% DV) "].apply(lambda x: x.replace('%','')))
df.groupby("Beverage")[" Calcium (% DV) "].mean()

Beverage
Banana Chocolate Smoothie                              20.000000
Brewed Coffee                                           0.500000
Caffè Americano                                         1.500000
Caffè Latte                                            35.000000
Caffè Mocha (Without Whipped Cream)                    30.000000
Cappuccino                                             22.500000
Caramel                                                11.000000
Caramel (Without Whipped Cream)                        12.000000
Caramel Apple Spice (Without Whipped Cream)             0.000000
Caramel Macchiato                                      28.333333
Coffee                                                 12.333333
Espresso                                                0.000000
Hot Chocolate (Without Whipped Cream)                  35.000000
Iced Brewed Coffee (With Classic Syrup)                 0.000000
Iced Brewed Coffee (With Milk & Classic Syrup)          8.000000
Java Chip       

In [202]:
# It's bulking season. What drink should Jackson get so that he maximizes protein but minimizes fat?
# (you can use more than one line for this one)
df[" Total Fat (g)"] = df[" Total Fat (g)"].apply(lambda x: x.replace(' ','.'))
df["ratio"] = df[" Protein (g) "]/np.float_(df[" Total Fat (g)"])+0.001
df[ df["ratio"] == df["ratio"].max() ]

Beverage_category  \
40   Classic Espresso Drinks   
41   Classic Espresso Drinks   
42   Classic Espresso Drinks   
43   Classic Espresso Drinks   
56   Classic Espresso Drinks   
57   Classic Espresso Drinks   
154    Shaken Iced Beverages   
169    Shaken Iced Beverages   
170    Shaken Iced Beverages   
171    Shaken Iced Beverages   

                                              Beverage Beverage_prep  \
40                                     Caffè Americano         Short   
41                                     Caffè Americano          Tall   
42                                     Caffè Americano        Grande   
43                                     Caffè Americano         Venti   
56                                            Espresso          Solo   
57                                            Espresso        Doppio   
154            Iced Brewed Coffee (With Classic Syrup)          Tall   
169  Shaken Iced Tazo® Tea Lemonade (With Classic S...          Tall   
170  Shaken Iced Tazo® Tea Lemonade (With Classic S...        Grande   
171  Shaken Iced Tazo® Tea Lemonade (With Classic S...         Venti   

     Calories  Total Fat (g)  Trans Fat (g)   Saturated Fat (g)   Sodium (mg)  \
40          5              0             0.0                0.0             0   
41         10              0             0.0                0.0             0   
42         15              0             0.0                0.0             0   
43         25              0             0.0                0.0             0   
56          5              0             0.0                0.0             0   
57         10              0             0.0                0.0             0   
154        60              0             0.0                0.0             0   
169       100              0             0.0                0.0             0   
170       130              0             0.0                0.0             0   
171       190              0             0.0                0.0             0   

      Total Carbohydrates (g)   Cholesterol (mg)   Dietary Fibre (g)  \
40                           5                 1                   0   
41                          10                 2                   0   
42                          15                 3                   0   
43                          15                 4                   0   
56                           0                 1                   0   
57                           1                 2                   0   
154                          4                15                   0   
169                          0                25                   0   
170                          0                33                   0   
171                          0                49                   0   

      Sugars (g)   Protein (g)  Vitamin A (% DV)  Vitamin C (% DV)  \
40             0            0.4                0%               0%   
41             0            1.0                0%               0%   
42             0            1.0                0%               0%   
43             0            1.0                0%               0%   
56             0            0.4                0%               0%   
57             0            1.0                0%               0%   
154           15            0.2                0%               0%   
169           24            0.1                0%              10%   
170           33            0.1                0%              15%   
171           49            0.1                0%              20%   

     Calcium (% DV)  Iron (% DV)  Caffeine (mg)  ratio  
40                0%           0%            75    inf  
41                2%           0%           150    inf  
42                2%           0%           225    inf  
43                2%           0%           300    inf  
56                0%           0%            75    inf  
57                0%           0%           150    inf  
154       